version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 8f147a9619094d86
      MYSQL_DATABASE: main
      MYSQL_USER: main
      MYSQL_PASSWORD: 8f147a9619094d86
    volumes:
      - ./data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
