version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 8f147a9619094d86
      MYSQL_DATABASE: main
      MYSQL_USER: main
      MYSQL_PASSWORD: 8f147a9619094d86
    volumes:
      - mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 3306:3306
      # - 33060:33060

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mysql

volumes:
  mysql:
